dataset:
  name: "phylake1337/fire-dataset" # kaggle_id, link: https://www.kaggle.com/datasets/phylake1337/fire-dataset
  ds_folder: "dataset"
  ds_local_path: "dataset/fire_dataset"

model:
  img_height: 224
  img_width: 224
  num_classes: 1 # 0: no fire, 1: fire

data_split:
  test_size: 0.15 
  validation_size: 0.15

training:
  batch_size: 32 # batch size
  initial_epochs: 10 # Num of epochs for learning feature extraction
  fine_tune_epochs: 20 # Num of epochs for fine-tuning
  initial_learning_rate: 0.001 # inital learn rate for feature extraction
  fine_tune_learning_rate: 0.0001 # learning rate for fine tuning
  early_stopping_patience: 10 # Num of epochs to execute before enable fine tuning
  reduce_lr_factor: 0.2 # Learning rate reduction factor
  reduce_lr_patience: 5 # Number of epochs without improvement before learning rate decreases
  min_lr: 0.000001 # Minimum learning rate for the initial stage
  min_lr_fine_tune: 0.0000001 # Minimum learning rate for fine-tuning
  unfreeze_layers_from_end: 50 # ufreezing last 50 layaers from the end

paths:
  model_save_path: "models"
  report_path: "reports/dataset_outcome_report.html"